services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: sa 
      MYSQL_DATABASE: personal_finance_management
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: personal_finance_management
      DB_USER: sa
      DB_PASSWORD: sa
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
